sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: |-
        g6Gpj2n1Bl6hIwWlywEkw8wRjpN2XuFsxFr9KQu/p7mRLYPdF3V5qQPVLBRd
        KvkjCIM7gZy2DTRNUooQPXdJB3npbnlbQn4jNWqA7/fp434Sw5sdfSUMawGr
        XvemLvn0KxQxCO9GfN3wfmYxEWJwXO36Q29BnRWWgMQOXpFFD8A=
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
  - mvn -B package
after_success:
  - mvn -B -Dmaven.test.skip=true -Dskip.web.build=true assembly:single
  - mvn -B -Dmaven.test.skip=true -Dskip.web.build=true --settings config/settings.xml deploy
deploy:
  provider: s3
  access_key_id: AKIAIGYGO43W76PZMMVA
  secret_access_key:
    secure: cYHsMgnAI08sz9G1Qb7ku2HoTaSn/OBBmjBzyYswX0/Kvb2asQcEGZGOEfYNTGOwdN6DP7p3axi5o+FPw2MLGGpBVz3tAtwYWTbzJR8kCEuGwb8N6abpdkGIn4AfifQ+vbn8zJrIB6HfGGRpDM9QnEjJFtpJO+2SjODzbZzkymE=
  bucket: graylog2-builds
  region: eu-west-1
  skip_cleanup: true
  local-dir: target/assembly
  on:
    repo: Graylog2/graylog2-server
    jdk: oraclejdk8
    branch:
      - master
      - 1.0
      - 1.1
      - 1.2
      - 1.3
      - 2.0
      - 2.1
      - 2.2
      - 2.3
      - 2.4
env:
  global:
  - secure: MYZwUwFkHwWfJ79JKyDK8VrYVcsax4t+7atMLLVNI4CDxTWZzR4qFGUfauf+7fDEmnGYbMHDRSnzzhVtSR0ZSuvWoSkZ+v62ASmSfglzI2GcMD/VBREq+9TlLasSIa+wR60VvgYwxJnawwJlV6sbjmetT6MWug7/icdi5KgfDlQ=
  - secure: r0enVlGBPjqaGfNrD1b6YxgRaSp/v39ZMKQFs/C0RtRKliZ5LVo7kS4lL0tLQoqMAXJel0NgsVH6j1P6428uLQDxqKmCsNZiX0VS9K3Z0iq5NG4x/5QidxyXjHefSGmpquLmZbM094xhtvdou3NEfkJTKbxHu3ML9i9ScMn5+vA=
  - secure: "OiqpeUFVXO/sWdSA4WZIrK5UvVUN4lG5YWm41e1P+6lvOAHpWeyX6fIs9Ndz12Vio/Wlt03ixzCAO/67UW4XGv/e3tClmvOSKt811Ml8wu3ALMxdV2218OkFXGzQ8AOnIRK1AAln3JdvBMHj8wFoUmGBaHJ7odqOxu3WC4m0Xr0="
  matrix:
  - GRAYLOG_ELASTICSEARCH_VERSION=5
