sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
before_deploy:
  - find . -type f -name 'original-*.jar' -delete
  - mvn jdeb:jdeb
  - mvn rpm:rpm
deploy:
  provider: releases
  api_key:
    secure: "T+ISAhBBXiRGSaLnUx2YXVO/DVYWN62EEiMU1rEzP+mJ2dh/GQfyNzZUJtIcaR0r++CcimZ6wc15+Ct4gJo7jOqQDEYonruuwAL3fD8RKv3Je4JlI2vxR5xu8KpKHpu6s246B5YzAVqWyi13PWQercOepkgXXYZaUelhacLn86XRkjAXR9NFxWb1TPtMLp+gdrYE5pmhhDh0r7IRnM5zmW5zhYL8N8byaDsKd90B1gjHkZhInC0Rw8iHTHiWcrPUZFhV4q5VLnFHI/OISqDfa28M6NyM5k/21Qc0dKdwDFi2X8wz2+iUcRKlYcnPoimBJtmIMdyGOBdshwU1Efn/Rztr0OMRc9gAjB4fcFzE1JyjP//8X8gCLWuSOshIS0oixht4vMLFYD42bBXRQm02lKF5mTMeLvD76fhmME6vKU6AL58vMceKOqdpRSAD0CxRogZ6CfVA86XOgKFGpMIbA+rivMV8DBvBpd15d8J4nFGbt4OTbr74Kr32gN9yKo9CjdezVO50QC3mBhSMo8ckD33OHbetoq075sHynFuxA4h/ALhfMl3cVchYXapUGpO9QAWXeqoqr8c75yAW+B9JI1lLGRwLb5I3FTRw4P0FsHOanQ0ltApEZHTvtE6YldQ57W99SAck/3LtpjpiuB0iIW/Std7UKHgS5/QPx3CxlEo="
  file_glob: true
  file:
    - "**/target/*.jar"
    - "**/target/*.deb"
    - "**/target/**/*.rpm"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
