name: "Changelog Check"

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "edited"

jobs:
  test:
    name: "Check Changelog presence"
    runs-on: "ubuntu-slim"

    steps:
      - uses: "Graylog2/actions/changelog-check@main"
