name: Fix linter hints

on:
  schedule:
    - cron: '0 */8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: graylog2-web-interface

    steps:
      - uses: actions/checkout@v2
      - name: Set up Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('graylog2-web-interface/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          path: ~/.cache/yarn
      - name: Install dependencies
        run: yarn install
      - name: Resetting lockfile
        run: git checkout yarn.lock
      - name: Run lint --fix
        continue-on-error: true
        run: yarn lint --fix -o /tmp/report.json -f json
      - name: Submit Results
        continue-on-error: true
        run: |
          PROBLEM_COUNT=`jq '. | map(.errorCount + .warningCount)|add' /tmp/report.json`
          CURRENT_REF=`git rev-parse HEAD`
          TIMESTAMP=`git show --format=%at $CURRENT_REF|head -1`
          PAYLOAD=$(cat <<- EOF
            {
              "version": "1.1",
              "host": "developermetrics",
              "job": "fix-linter-hints",
              "short_message": "Found ${PROBLEM_COUNT} problems in commit ${CURRENT_REF}",
              "_problems": ${PROBLEM_COUNT},
              "_current_ref": "${CURRENT_REF}",
              "timestamp": ${TIMESTAMP}
             }
          EOF
          )
          curl -X POST -H 'Content-Type: application/json' -d $PAYLOAD ${{ secrets.DEV_METRICS_URL }}
      - name: Create/Update Pull Request
        uses: Graylog2/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          title: Fixing linter hints automatically
          body: This PR was created by a job that is running periodically to find and fix linter hints.
          author: Dr. Lint-a-lot <garybot2@graylog.com>
          branch: fix/linter-hints
          committer: Dr. Lint-a-lot <garybot2@graylog.com>
          commit-message: Running lint --fix
          delete-branch: true
