type = "a"
message = "Add default 30-day time range filter to Security Alerts Entity Table"

pulls = ["graylog2-server#24911", "graylog-plugin-enterprise#13100"]
issues = ["Graylog2/graylog2-server/issues/24887"]
