type = "fixed"
message = "Removes replay info from events for the FE where the eventdefinition no longer exists. No replay is possible in that case so the replay button is disabled."

issues = ["18931"]
pulls = ["24193", "Graylog2/graylog-plugin-enterprise#12489"]
