type = "c" # One of: a(dded), c(hanged), d(eprecated), r(emoved), f(ixed), s(ecurity)
message = "Restructure layout of users edit and details view."

issues = ["graylog-plugin-enterprise#12002"]
pulls = ["24116"]
