type = "Added" # One of: a(dded), c(hanged), d(eprecated), r(emoved), f(ixed), s(ecurity)
message = "Adds a deprecated label to rules and pipelines which shows deprecated functions used in those."

issues = ["23924"]
pulls = ["24018"]
