type = "f"
message = "Move index range calculation on index rotation into current scheduler so it persists and survives server restarts."

pulls = ["24377", "Graylog2/graylog-plugin-enterprise#12638"]
