# PLEASE REMOVE COMMENTS AND OPTIONAL FIELDS! THANKS!

# Entry type according to https://keepachangelog.com/en/1.0.0/
# One of: a(dded), c(hanged), d(eprecated), r(emoved), f(ixed), s(ecurity)
type = "fixed"
message = "Fix protocol version negotiation for MCP server."

issues = ["24701"]
pulls = ["24717"]

contributors = [""]

details.user = """
This text contains a more detailed description of the change for users.

It can be written in Markdown to support [links](https://example.com) and
other elements.
"""

details.ops = """
This text contains operations related details for the change.

It can be written in Markdown to support [links](https://example.com) and
other elements.
"""
